HH-80991 allow to wait preprocessors requests completion
hhru/frontik pull request #379
Opened 2018-07-14 23:13 UTC by bokshitsky

https://jira.hh.ru/browse/HH-80991

2018-07-14 23:18 UTC, bokshitsky commented on frontik/handler.py
> +        return future
По идее, этом опасно использовать с произвольной future-й - если нет детерменизма в вызове колбеков на ивен-лупе - может быть ситуация, когда завершение `preprocessors_completed_group` группы вызовется раньше callback-а определнного в `get_url` 

Для нашей реализации - это безопасно, коллбек-функция вызывается синхронно:
https://github.com/hhru/frontik/blob/ad85d70da3fdb5e38524bfe7ca5ed7bf2f0e42ba/frontik/http_client/__init__.py#L580-L583
после чего фьюча комплитится

поэтому метод и назвал `add_REQUEST_to_preprocessors_completed_group`
альтернатива - в каждом препроцессоре, в котором нужно, коллбек обернуть в `self.preprocessors_completed_group.add`

2018-07-16 07:20 UTC, bokshitsky commented
Первый коммит про асинк-группу
Второй про упрощение кода `preprocessor`

2018-07-16 09:51 UTC, SuminAndrew requested changes

2018-07-16 09:51 UTC, SuminAndrew commented on frontik/handler.py
> +    def add_request_to_preprocessors_completed_group(self, future):
лучше покороче) add_request_to_preprocessors_completed_group -> add_to_preprocessors_group
т.к. ты не request добавляешь, а фьючу, а completed вовсе лишнее (см. finish_group)

2018-07-16 09:51 UTC, SuminAndrew commented on frontik/handler.py
> +    def add_request_to_preprocessors_completed_group(self, future):
ну и все остальное так же preprocessors_completed_group -> preprocessors_group итд, читать станет полегче

2018-07-16 09:51 UTC, SuminAndrew commented on frontik/handler.py
> +        self.preprocessors_completed_group = AsyncGroup(preprocessors_completed_callback, name='finish preprocessors')
name будет фигурировать в логах, поэтому запись "finish preprocessors group: ..." будет выглядеть странновато
если это группа для препроцессоров, то давай и называть её 'preprocessors'

2018-07-16 09:51 UTC, SuminAndrew commented on frontik/handler.py
> +    def add_request_to_preprocessors_completed_group(self, future):
и этот метод лучше поближе к # Preprocessors and postprocessors поселить

2018-07-16 09:51 UTC, SuminAndrew commented on frontik/handler.py
> +        def _handle_preprocessors_future(future):
тут похоже не обрабатывается результат future
если в ней лежит False, то page-метод не вызывается (это осталось в рабочем состоянии, т.к. ты прокидываешь фьючу во wrapped_page_handler_method), но наверное также нужно принудительно завершить preprocessors_completed_group

2018-07-16 09:51 UTC, SuminAndrew commented on frontik/handler.py
> +        self.add_future(self._run_preprocessors(preprocessors, self), _handle_preprocessors_future)
по идее этот метод — обертка над _run_preprocessors
раньше было "выполни препроцессоры", теперь — "выполни препроцессоры и подожди препроцессорную группу"
смысла разделять их нет, так только запутаннее становится и теряются некоторые кейсы (с обработкой препроцессорной фьючи например)

лучше унести этот код в _run_preprocessors, пусть создает асинкгруппу в начале, а в конце перед gen.Return(True) делает yield фьючи (которая резолвится при завершении асинкгруппы)
так выглядит гораздо проще

2018-07-16 09:51 UTC, SuminAndrew commented on frontik/handler.py
> +        self.add_future(self._run_preprocessors(preprocessors, self), _handle_preprocessors_future)
вообще идеально было бы добавить в асникгруппу пару методов add_future (который ты бы вызывал в add_request_to_preprocessors_completed_group) и get_future (которую ты бы yieldил перед gen.Return(True))

2018-07-16 13:48 UTC, SuminAndrew commented on frontik/async.py
> +        future.add_done_callback(self.add_notification())
лучше IOLoop.current().add_future() — иначе эксепшены (мало ли что там) проглатываются

2018-07-16 13:49 UTC, SuminAndrew commented on frontik/async.py
> +    def get_group_future(self):
давай get_finish_future назовём, по аналогии с finish_cb

2018-07-16 13:50 UTC, bokshitsky commented on frontik/async.py
> +    def get_group_future(self):
Ну она путаться будет с какой-нибудь page.finish

2018-07-16 13:53 UTC, SuminAndrew commented on frontik/handler.py
> +        preprocessors_group_notification()
пару тестиков хорошо бы на новый метод add_to_preprocessors_group и механизм в целом!

2018-07-16 14:44 UTC, bokshitsky commented on tests/projects/test_app/pages/preprocessors_group.py
> +    @waiting_preprocessor(2.0, "should_finish_third", True)
нехорошо, конечно, писать такие тесты, но с другой стороны, вероятность, что на них гонка сработает очень мала

2018-07-16 14:56 UTC, SuminAndrew commented on tests/projects/test_app/pages/preprocessors_group.py
> +    @waiting_preprocessor(5.0, "should_finish_after_page_finish", False)
:sob: двухсекундный тест?
может что-то побыстрее придумать?) 5 штук препроцессоров точно нужно для теста?

2018-07-16 15:47 UTC, bokshitsky commented on tests/projects/test_app/pages/preprocessors_group.py
> +    @waiting_preprocessor(5.0, "should_finish_after_page_finish", False)
2 секунды это не 2 года)
Ну хочется именно столько, чтобы убедиться, то порядок их прохождения вызван не просто удачным расположением изначальным

2018-07-17 17:37 UTC, merged