HH-120081 fix serviceId
hhru/frontik pull request #485
Opened 2020-11-20 14:19 UTC by dzharikhin

2020-11-23 13:02 UTC, Aulust approved these changes

2020-11-23 13:08 UTC, disarmer approved these changes

2020-11-23 16:51 UTC, sintell commented on docker/Dockerfile.building
> +FROM registry.pyn.ru/python3.7-node-ubuntu18-production:2020.08.21
это лишнее, для фронтика должно быть достаточно просто питонячего контейнера

2020-11-23 16:52 UTC, dzharikhin commented on docker/Dockerfile.building
> +FROM registry.pyn.ru/python3.7-node-ubuntu18-production:2020.08.21
а я че т гляжу - давно не собирали

2020-11-23 16:54 UTC, sintell commented on setup.py
> +    install_requires=requirements_txt,
А вот это, скорее всего, не работает. У тебя `requirements_txt` будет виден только в пределах блока `with`

2020-11-23 16:55 UTC, sintell requested changes

2020-11-23 16:55 UTC, sintell commented on setup.py
> +    install_requires=requirements_txt,
ты хотел сюда `install_requirements` написать

2020-11-23 17:01 UTC, sintell commented on docker/Dockerfile.building
> +FROM registry.pyn.ru/python3.7-node-ubuntu18-production:2020.08.21
это для xhh, где в одном контейнере живут фронтик и нодик

2020-11-23 17:06 UTC, dzharikhin commented on docker/Dockerfile.building
> +FROM registry.pyn.ru/python3.7-node-ubuntu18-production:2020.08.21
и то уже нет вроде

2020-11-24 08:08 UTC, Aulust approved these changes

2020-11-24 10:55 UTC, vera-l commented on setup.py
> +    print("foooo")
??

2020-11-24 10:56 UTC, dzharikhin commented on setup.py
> +    print("foooo")
пофиксил чуть раньше)

2020-11-24 11:01 UTC, vera-l commented on requirements.txt
> +tornado @ https://github.com/hhru/tornado/archive/master.zip
а так не работает?
```
git+ssh://github.com/hhru/balancing-http-client@1.0.1#egg=balancing-http-client
```

2020-11-24 11:01 UTC, vera-l approved these changes
вроде ок

2020-11-24 11:02 UTC, dzharikhin commented on requirements.txt
> +tornado @ https://github.com/hhru/tornado/archive/master.zip
в setuptools вроде фейлится такой формат

2020-11-24 11:02 UTC, dzharikhin commented on requirements.txt
> +tornado @ https://github.com/hhru/tornado/archive/master.zip
а мы этот список и там и тут держим - ну вернее отсюда туда его подставляем

2020-11-24 11:34 UTC, merged