HH-200459 allow to return value from handler
hhru/frontik pull request #669
Opened 2023-12-04 07:37 UTC by bokshitsky

- HH-200459 remove _exception_hooks
- HH-200459 simplify _encode_value
- HH-200459 allow to return value from handler
- HH-200459 run_server is not async

2023-12-04 07:40 UTC, bokshitsky commented on frontik/server.py
> +def run_server(
это чутка на будущее

2023-12-04 07:44 UTC, bokshitsky commented on frontik/handler.py
> -    def register_exception_hook(self, exception_hook):
нигде в hh не юзается, при этом сделан как-то не очень подходяще (через log_exception), лучше удалю чтобы не мешался. Если захотим делать exception-catcher-ы, подумаем, как это лучше организовать

2023-12-04 07:46 UTC, bokshitsky commented on frontik/json_builder.py
> +        return {k: _encode_value(v) for k, v in value.items()}
типа меньше кода - лучше дышится

2023-12-05 11:42 UTC, 712u3 requested changes

2023-12-05 11:42 UTC, 712u3 commented on frontik/app.py
> +        tornado_settings = settings.get('tornado_settings') or {}
а мы вроде их вообще не юзаем, может можно удалить?

2023-12-05 11:44 UTC, bokshitsky commented on frontik/app.py
> +        tornado_settings = settings.get('tornado_settings') or {}
в поиске нашел, решил не трогать.
https://github.com/search?q=org%3Ahhru%20tornado_settings&type=code

2023-12-05 11:58 UTC, 712u3 approved these changes

2023-12-05 20:51 UTC, merged